/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
import { BorderStyle } from './border-style';
export class Border { 

    @Expose()
    Bottom?: BorderStyle | null = null;
    @Expose()
    Left?: BorderStyle | null = null;
    @Expose()
    Right?: BorderStyle | null = null;
    @Expose()
    Top?: BorderStyle | null = null;
}

// ---------------------------