/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
/**
 * CalendarRowStyle
 * @export
 * @enum {string}
 */
export enum CalendarRowStyle {
    MonthMMM = 'MonthMMM',
    MonthMM = 'MonthMM',
    PeriodMonthP1 = 'PeriodMonthP1',
    PeriodWeekOneXOne = 'PeriodWeekOneXOne',
    QuarterQ1 = 'QuarterQ1',
    WeekDD = 'WeekDD',
    YearYYYY = 'YearYYYY',
    YearYY = 'YearYY'
}


// ---------------------------