/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
import { CalendarOverlayRow } from './calendar-overlay-row';
import { Styling } from './styling';
export class CalendarOverlaySection { 

    /**
     * Gets or sets the order.
     */
    @Expose()
    Order: number | null = null;
    /**
     * Gets or sets the rows.
     */
    @Expose()
    @Type(() => CalendarOverlayRow)
    Rows: Array<CalendarOverlayRow> | null = null;
    @Expose()
    Styling?: Styling | null = null;
    /**
     * Gets or sets the text.
     */
    @Expose()
    Text: string | null = null;
}

// ---------------------------