/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
import { CalendarConfiguration } from './calendar-configuration';
import { Styling } from './styling';
export class CalendarDefinition { 

    @Expose()
    Configuration: CalendarConfiguration | null = null;
    @Expose()
    Styling: Styling | null = null;
}

// ---------------------------