/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
import { UserInfoDTO } from './user-info-dto';
export class CalendarTemplateInfoDTO { 

    @Expose()
    CreatedByUser?: UserInfoDTO | null = null;
    /**
     * Gets or sets the created date.
     */
    @Expose()
    CreatedDate?: Date | null = null;
    @Expose()
    ModifiedByUser?: UserInfoDTO | null = null;
    /**
     * Gets or sets the modified date.
     */
    @Expose()
    ModifiedDate?: Date | null = null;
    /**
     * Gets or sets the version.
     */
    @Expose()
    Version?: number | null = null;
    /**
     * Gets or sets a value indicating whether gets or sets the IsDefault identifier.
     */
    @Expose()
    IsDefault?: boolean | null = null;
    /**
     * Gets or sets the name.
     */
    @Expose()
    Name?: string | null = null;
    /**
     * Gets or sets the identifier.
     */
    @Expose()
    Id?: string | null = null;
    /**
     * Gets or sets a value indicating whether this Lib.WebAPI.DTOs.ModelBaseDTO is  removed.
     */
    @Expose()
    Removed?: boolean | null = null;
}

// ---------------------------