/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
import { CalendarRowStyle } from './calendar-row-style';
import { StandardCalenderRowType } from './standard-calender-row-type';
import { Styling } from './styling';
export class CalendarRow { 

    /**
     * Gets or sets the name of the column.
     */
    @Expose()
    ColumnName?: string | null = null;
    /**
     * Gets or sets the order.
     */
    @Expose()
    Order: number | null = null;
    @Expose()
    StandardCalenderRowType?: StandardCalenderRowType | null = null;
    @Expose()
    Style: CalendarRowStyle | null = null;
    @Expose()
    Styling?: Styling | null = null;
}

// ---------------------------