/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
import { ColumnType } from './column-type';
export class DataDictionaryColumnDetailsDTO { 

    /**
     * Gets or sets the display name.
     */
    @Expose()
    DisplayName?: string | null = null;
    /**
     * Gets or sets the name.
     */
    @Expose()
    Name?: string | null = null;
    @Expose()
    Type?: ColumnType | null = null;
}

// ---------------------------