/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
import { FlowchartData } from './flowchart-data';
import { HeaderData } from './header-data';
import { SummaryData } from './summary-data';
export class Data { 

    @Expose()
    FlowchartData?: FlowchartData | null = null;
    @Expose()
    HeaderData?: HeaderData | null = null;
    @Expose()
    SummaryData?: SummaryData | null = null;
}

// ---------------------------