/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
/**
 * Represents options for column name display.
 * @export
 * @enum {string}
 */
export enum DisplaySource {
    PlanitField = 'PlanitField',
    PlanningSystem = 'PlanningSystem',
    PlanitClientAlias = 'PlanitClientAlias'
}


// ---------------------------