/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
export class FieldInfo { 

    /**
     * Gets or sets the type identifier.
     */
    @Expose()
    Type?: string | null = null;
    /**
     * Gets or sets a value indicating whether gets or sets the type identifier.
     */
    @Expose()
    IsMetric?: boolean | null = null;
    /**
     * Gets or sets a value indicating whether gets or sets the IsCurrency identifier.
     */
    @Expose()
    IsCurrency?: boolean | null = null;
    /**
     * Gets or sets a value indicating whether gets or sets the IsCommon identifier.
     */
    @Expose()
    IsCommon?: boolean | null = null;
    /**
     * Gets or sets the moduleType identifier.
     */
    @Expose()
    ModuleType?: string | null = null;
    /**
     * Gets or sets the name.
     */
    @Expose()
    Name: string | null = null;
    /**
     * Gets or sets the identifier.
     */
    @Expose()
    Id?: string | null = null;
    /**
     * Gets or sets a value indicating whether this Lib.WebAPI.DbModels.DbModelBase is  removed.
     */
    @Expose()
    Removed?: boolean | null = null;
}

// ---------------------------