/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
import { FlightRange } from './flight-range';
import { FlowchartDataMetric } from './flowchart-data-metric';
import { FlowchartDataSubTotal } from './flowchart-data-sub-total';
import { FlowchartDataTotal } from './flowchart-data-total';
 export class FlowchartDataSubLevel {

    /**
     * Gets or sets the name of the column.
     */
    @Expose()
    ColumnName?: string | null = null;
    @Expose()
    FlightRange?: FlightRange | null = null;
    /**
     * Gets or sets the name of the metric column.
     */
    @Expose()
    MetricColumnName?: string | null = null;
    /**
     * Gets or sets the metrics.
     */
    @Expose()
    @Type(() => FlowchartDataMetric)
    Metrics?: Array<FlowchartDataMetric> | null = null;
    /**
     * Gets or sets the metric table identifier.
     */
    @Expose()
    MetricTableId?: string | null = null;
    /**
     * Gets or sets the name.
     */
    @Expose()
    Name?: string | null = null;
    /**
     * Gets or sets the order.
     */
    @Expose()
    Order?: number | null = null;
    /**
     * Gets or sets the sub levels.
     */
    @Expose()
    @Type(() => FlowchartDataSubLevel)
    SubLevels?: Array<FlowchartDataSubLevel> | null = null;
    /**
     * Gets or sets the sub totals.
     */
    @Expose()
    @Type(() => FlowchartDataSubTotal)
    SubTotals?: Array<FlowchartDataSubTotal> | null = null;
    /**
     * Gets or sets the table identifier.
     */
    @Expose()
    TableId?: string | null = null;
    /**
     * Gets or sets the totals.
     */
    @Expose()
    @Type(() => FlowchartDataTotal)
    Totals?: Array<FlowchartDataTotal> | null = null;
    /**
     * Gets or sets the totals.
     */
    @Expose()
    @Type(() => FlowchartDataTotal)
    BriefedCtcTotals?: Array<FlowchartDataTotal> | null = null;
}

// ---------------------------