/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
import { FlowchartDataLevel } from './flowchart-data-level';
import { GrandTotalData } from './grand-total-data';
export class FlowchartData { 

    /**
     * Gets or sets the grand totals.
     */
    @Expose()
    @Type(() => GrandTotalData)
    GrandTotals?: Array<GrandTotalData> | null = null;
    /**
     * Gets or sets the levels.
     */
    @Expose()
    @Type(() => FlowchartDataLevel)
    Levels?: Array<FlowchartDataLevel> | null = null;
    /**
     * Gets or sets the RawData.
     */
    @Expose()
    RawData?: Array<{ [key: string]: any; }> | null = null;
}

// ---------------------------