/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
import { ComponentInfo } from './component-info';
export class FlowChartTemplateShareDetailsDTO { 

    /**
     * Gets or sets the CurrentOmniGuid.
     */
    @Expose()
    CurrentOmniClientId?: string | null = null;
    /**
     * Gets or sets the NewOmniClientId.
     */
    @Expose()
    NewOmniClientId?: string | null = null;
    /**
     * Gets or sets the NewTemplateName.
     */
    @Expose()
    NewTemplateName?: string | null = null;
    /**
     * Gets or sets the TemplateId.
     */
    @Expose()
    TemplateId?: string | null = null;
    /**
     * Gets or sets the ComponentInfosList.
     */
    @Expose()
    @Type(() => ComponentInfo)
    ComponentInfosList?: Array<ComponentInfo> | null = null;
}

// ---------------------------