/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
import { ClientDetails } from './client-details';
import { ComponentDetails } from './component-details';
export class FlowchartTemplateShareInfoDTO { 

    /**
     * Gets or sets the component details.
     */
    @Expose()
    @Type(() => ComponentDetails)
    ComponentDetailsList?: Array<ComponentDetails> | null = null;
    /**
     * Gets or sets the client details.
     */
    @Expose()
    @Type(() => ClientDetails)
    ClientDetailsList?: Array<ClientDetails> | null = null;
    /**
     * Gets or sets the TemplateName.
     */
    @Expose()
    TemplateName?: string | null = null;
    /**
     * Gets or sets the TemplateId.
     */
    @Expose()
    TemplateId?: string | null = null;
    /**
     * Gets or sets the parentId.
     */
    @Expose()
    ParentId?: string | null = null;
}

// ---------------------------