/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
export class FlowchartDataDictionaryColumnDetails { 

    @Expose()
    TableId?: string | null = null;
    @Expose()
    TableName?: string | null = null;
    @Expose()
    ColumnName?: string | null = null;
    @Expose()
    DisplayName?: string | null = null;
    @Expose()
    ColumnType?: string | null = null;
    @Expose()
    IsCommon?: boolean | null = null;
    @Expose()
    IsCurrency?: boolean | null = null;
    @Expose()
    IsMetric?: boolean | null = null;
}

// ---------------------------