/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
import { Color } from './color';
import { FontWeight } from './font-weight';
import { RangeUnderlineStyle } from './range-underline-style';
export class Font { 

    @Expose()
    Background?: Color | null = null;
    @Expose()
    BackgroundAlternate?: Color | null = null;
    @Expose()
    Color?: Color | null = null;
    @Expose()
    ColorAlternate?: Color | null = null;
    /**
     * Gets or sets the family.
     */
    @Expose()
    Family?: string | null = null;
    /**
     * Gets or sets the size.
     */
    @Expose()
    Size?: number | null = null;
    @Expose()
    Underline?: RangeUnderlineStyle | null = null;
    @Expose()
    Weight?: FontWeight | null = null;
}

// ---------------------------