/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
import { FooterTemplateInfoDTO } from './footer-template-info-dto';
export class FooterTemplateInfoListDTO { 

    /**
     * Gets or sets the items.
     */
    @Expose()
    @Type(() => FooterTemplateInfoDTO)
    Items?: Array<FooterTemplateInfoDTO> | null = null;
    /**
     * Gets or sets the total count.
     */
    @Expose()
    TotalCount?: number | null = null;
}

// ---------------------------