/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
import { HeaderDetails } from './header-details';
import { HeaderLogo } from './header-logo';
import { HeaderRow } from './header-row';
import { HeaderRowMerge } from './header-row-merge';
export class HeaderConfiguration { 

    /**
     * Gets or sets the column margin.
     */
    @Expose()
    ColumnMargin: number | null = null;
    @Expose()
    Details?: HeaderDetails | null = null;
    /**
     * Gets or sets the logos.
     */
    @Expose()
    @Type(() => HeaderLogo)
    Logos?: Array<HeaderLogo> | null = null;
    /**
     * Gets or sets the row margin.
     */
    @Expose()
    RowMargin: number | null = null;
    @Expose()
    RowMerge: HeaderRowMerge | null = null;
    /**
     * Gets or sets the rows.
     */
    @Expose()
    @Type(() => HeaderRow)
    Rows: Array<HeaderRow> | null = null;
}

// ---------------------------