/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
/**
 * Horizontal alignment.
 * @export
 * @enum {string}
 */
export enum HorizontalAlignment {
    General = 'General',
    Left = 'Left',
    Center = 'Center',
    Right = 'Right',
    Fill = 'Fill',
    Justify = 'Justify',
    CenterAcrossSelection = 'CenterAcrossSelection',
    Distributed = 'Distributed'
}


// ---------------------------