/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
import { Styling } from './styling';
export class LegendThemeSetting { 

    @Expose()
    Styling: Styling | null = null;
    /**
     * Gets or sets a value indicating whether this Lib.WebAPI.Models.Flowchart.LegendThemeSetting is enabled.
     */
    @Expose()
    Enabled?: boolean | null = null;
    /**
     * Gets or sets the name.
     */
    @Expose()
    Name: string | null = null;
    @Expose()
    InflightOverlayStyling?: Styling | null = null;
    @Expose()
    SubTotalStyling?: Styling | null = null;
}

// ---------------------------