/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
import { MediaHierarchySubLevelSettingBase } from './media-hierarchy-sub-level-setting-base';
import { MediaHierarchySubTotalBase } from './media-hierarchy-sub-total-base';
export class MediaHierarchySubLevelBase { 

    /**
     * Gets or sets the name of the column.
     */
    @Expose()
    ColumnName: string | null = null;
    /**
     * Gets or sets the order.
     */
    @Expose()
    Order: number | null = null;
    /**
     * Gets or sets the settings.
     */
    @Expose()
    @Type(() => MediaHierarchySubLevelSettingBase)
    Settings: Array<MediaHierarchySubLevelSettingBase> | null = null;
    /**
     * Gets or sets the sub totals.
     */
    @Expose()
    @Type(() => MediaHierarchySubTotalBase)
    SubTotals?: Array<MediaHierarchySubTotalBase> | null = null;
    /**
     * Gets or sets the table identifier.
     */
    @Expose()
    TableId: string | null = null;
}

// ---------------------------