/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
import { FlightRange } from './flight-range';
import { MediaHierarchyInflightOverlay } from './media-hierarchy-inflight-overlay';
import { MediaHierarchySubLevel } from './media-hierarchy-sub-level';
import { MediaHierarchySubTotal } from './media-hierarchy-sub-total';
import { MediaHierarchySubTotalSummary } from './media-hierarchy-sub-total-summary';
import { Styling } from './styling';
export class MediaHierarchySetting { 

    @Expose()
    Styling?: Styling | null = null;
    @Expose()
    InflightOverlayStyling?: Styling | null = null;
    /**
     * Gets or sets a value indicating whether this Lib.WebAPI.Models.Flowchart.MediaHierarchySetting is enabled.
     */
    @Expose()
    Enabled: boolean | null = null;
    @Expose()
    FlightRange: FlightRange | null = null;
    /**
     * Gets or sets the name of the inflight overlay column.
     */
    @Expose()
    InflightOverlayColumnName?: string | null = null;
    /**
     * Gets or sets the inflight overlay table identifier.
     */
    @Expose()
    InflightOverlayTableId?: string | null = null;
    /**
     * Gets or sets the name of the metric column.
     */
    @Expose()
    MetricColumnName?: string | null = null;
    /**
     * Gets or sets the metric table identifier.
     */
    @Expose()
    MetricTableId?: string | null = null;
    /**
     * Gets or sets the name.
     */
    @Expose()
    Name: string | null = null;
    /**
     * Gets or sets the order.
     */
    @Expose()
    Order: number | null = null;
    /**
     * Gets or sets the sub levels.
     */
    @Expose()
    @Type(() => MediaHierarchySubLevel)
    SubLevels?: Array<MediaHierarchySubLevel> | null = null;
    /**
     * Gets or sets the sub totals.
     */
    @Expose()
    @Type(() => MediaHierarchySubTotal)
    SubTotals?: Array<MediaHierarchySubTotal> | null = null;
    /**
     * Gets or sets the inflight overlays.
     */
    @Expose()
    @Type(() => MediaHierarchyInflightOverlay)
    InflightOverlays?: Array<MediaHierarchyInflightOverlay> | null = null;
    /**
     * Gets or sets the sub totals summary.
     */
    @Expose()
    @Type(() => MediaHierarchySubTotalSummary)
    SubTotalSummary?: Array<MediaHierarchySubTotalSummary> | null = null;
}

// ---------------------------