/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
import { MediaHierarchySubTotalBase } from './media-hierarchy-sub-total-base';
import { MediaHierarchySubTotalSummarySettingBase } from './media-hierarchy-sub-total-summary-setting-base';
export class MediaHierarchySubTotalSummaryBase { 

    /**
     * Gets or sets the sub totals.
     */
    @Expose()
    @Type(() => MediaHierarchySubTotalBase)
    SubTotals?: Array<MediaHierarchySubTotalBase> | null = null;
    /**
     * Gets or sets the settings.
     */
    @Expose()
    @Type(() => MediaHierarchySubTotalSummarySettingBase)
    Settings?: Array<MediaHierarchySubTotalSummarySettingBase> | null = null;
}

// ---------------------------