/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
import { MediaHierarchyColumnAndTableDetails } from './media-hierarchy-column-and-table-details';
export class MediaHierarchyColumnsDetailsDTO { 

    /**
     * Gets or sets the OmniClientId identifier.
     */
    @Expose()
    OmniClientId?: string | null = null;
    /**
     * Gets or sets the ClientName.
     */
    @Expose()
    ClientName?: string | null = null;
    /**
     * Gets or sets the ClientId.
     */
    @Expose()
    ClientId?: string | null = null;
    /**
     * Gets or sets the name of the column.
     */
    @Expose()
    @Type(() => MediaHierarchyColumnAndTableDetails)
    ColumnInfos?: Array<MediaHierarchyColumnAndTableDetails> | null = null;
}

// ---------------------------