/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
import { Styling } from './styling';
export class MediaHierarchyInflightOverlay { 

    @Expose()
    Styling?: Styling | null = null;
    /**
     * Gets or sets the name of the column.
     */
    @Expose()
    ColumnName: string | null = null;
    /**
     * Gets or sets the order.
     */
    @Expose()
    Order: number | null = null;
    /**
     * Gets or sets the table identifier.
     */
    @Expose()
    TableId: string | null = null;
}

// ---------------------------