/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
export class PlannedMediaMigrationColumnMapping { 

    /**
     * Gets or sets the sourceColumnName identifier.
     */
    @Expose()
    SourceColumnName?: string | null = null;
    /**
     * Gets or sets the sourceTableId identifier.
     */
    @Expose()
    SourceTableId?: string | null = null;
    /**
     * Gets or sets the destinationColumnName identifier.
     */
    @Expose()
    DestinationColumnName?: string | null = null;
    /**
     * Gets or sets the destinationTableId identifier.
     */
    @Expose()
    DestinationTableId?: string | null = null;
    /**
     * Gets or sets the client identifier.
     */
    @Expose()
    OmniClientId?: string | null = null;
    /**
     * Gets or sets the identifier.
     */
    @Expose()
    Id?: string | null = null;
    /**
     * Gets or sets a value indicating whether this Lib.WebAPI.DbModels.DbModelBase is  removed.
     */
    @Expose()
    Removed?: boolean | null = null;
}

// ---------------------------