/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
/**
 * Range Underline Style
 * @export
 * @enum {string}
 */
export enum RangeUnderlineStyle {
    None = 'None',
    Single = 'Single',
    Double = 'Double',
    SingleAccountant = 'SingleAccountant',
    DoubleAccountant = 'DoubleAccountant'
}


// ---------------------------