/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
import { CalendarTemplateDetailsDTO } from './calendar-template-details-dto';
import { MediaHierarchyLevelBase } from './media-hierarchy-level-base';
import { RunRestriction } from './run-restriction';
export class RunConfigurationUpdateDTO { 

    /**
     * Gets or sets the identifier.
     */
    @Expose()
    Id: string | null = null;
    @Expose()
    CalendarDefinition?: CalendarTemplateDetailsDTO | null = null;
    /**
     * Gets or sets the media hierarchy levels.
     */
    @Expose()
    @Type(() => MediaHierarchyLevelBase)
    MediaHierarchyLevels: Array<MediaHierarchyLevelBase> | null = null;
    /**
     * Gets or sets the name.
     */
    @Expose()
    Name: string | null = null;
    /**
     * Gets or sets the run restrictions.
     */
    @Expose()
    @Type(() => RunRestriction)
    RunRestrictions: Array<RunRestriction> | null = null;
    /**
     * Gets or sets the run configuration comments.
     */
    @Expose()
    Comments?: string | null = null;
    /**
     * Gets or sets the Custom Style Settings.
     */
    @Expose()
    CustomStyleSettings?: string | null = null;
    /**
     * Gets or sets the Track Changes.
     */
    @Expose()
    TrackFormatChanges?: boolean | null = null;
}

// ---------------------------