/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
import { Styling } from './styling';
import { SummaryRow } from './summary-row';
export class SummaryDefinition { 

    /**
     * Gets or sets the rows.
     */
    @Expose()
    @Type(() => SummaryRow)
    Rows: Array<SummaryRow> | null = null;
    @Expose()
    Styling?: Styling | null = null;
}

// ---------------------------