/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
import { CalendarConfiguration } from './calendar-configuration';
import { RunRestriction } from './run-restriction';
import { SummaryDefinition } from './summary-definition';
export class SummaryDataRequestDTO { 

    @Expose()
    CalendarConfiguration: CalendarConfiguration | null = null;
    /**
     * Gets or sets the client identifier.
     */
    @Expose()
    OmniClientId: string | null = null;
    /**
     * Gets or sets the run restrictions.
     */
    @Expose()
    @Type(() => RunRestriction)
    RunRestrictions: Array<RunRestriction> | null = null;
    @Expose()
    SummaryDefinition: SummaryDefinition | null = null;
}

// ---------------------------