/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
/**
 * Represents status for template shared and received.
 * @export
 * @enum {string}
 */
export enum TemplateShareStatus {
    None = 'None',
    Shared = 'Shared',
    Received = 'Received'
}


// ---------------------------