/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
import { ThemeTemplateInfoDTO } from './theme-template-info-dto';
export class ThemeTemplateInfoListDTO { 

    /**
     * Gets or sets the items.
     */
    @Expose()
    @Type(() => ThemeTemplateInfoDTO)
    Items?: Array<ThemeTemplateInfoDTO> | null = null;
    /**
     * Gets or sets the total count.
     */
    @Expose()
    TotalCount?: number | null = null;
}

// ---------------------------