/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
import { TotalsDefinition } from './totals-definition';
export class TotalsTemplateCreateDTO { 

    @Expose()
    Definition: TotalsDefinition | null = null;
    /**
     * Gets or sets the name.
     */
    @Expose()
    Name: string | null = null;
    /**
     * Gets or sets the client identifier.
     */
    @Expose()
    OmniClientId: string | null = null;
    /**
     * Gets or sets a value indicating whether gets or sets the IsDefault identifier.
     */
    @Expose()
    IsDefault?: boolean | null = null;
}

// ---------------------------