/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import { Type, Expose } from 'class-transformer';
// @dynamic

// -------------------------------
export class ValidateSessionResponse { 

    /**
     * Gets or sets a value indicating whether this instance is authorized.
     */
    @Expose()
    IsAuthorized?: boolean | null = null;
    /**
     * Gets or sets the person identifier.
     */
    @Expose()
    PersonId?: string | null = null;
}

// ---------------------------