/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { CalendarOverlayTemplateCreateDTO } from '../models';
import { CalendarOverlayTemplateDetailsDTO } from '../models';
import { CalendarOverlayTemplateInfoDTO } from '../models';
import { CalendarOverlayTemplateInfoListDTO } from '../models';
import { CalendarOverlayTemplateSearchDTO } from '../models';
import { CalendarOverlayTemplateUpdateDTO } from '../models';
import { DuplicateNameCheckDto } from '../models';
import { ExceptionDTO } from '../models';
/**
 * CalendarOverlayTemplateApi - axios parameter creator
 * @export
 */
export const CalendarOverlayTemplateApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Check the duplicate calendar overlay component name.
         * @param {DuplicateNameCheckDto} [body] The duplicate name check Dto.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calendarOverlayTemplateCheckDuplicateComponentName: async (body?: DuplicateNameCheckDto, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/CalendarOverlayTemplate/CheckDuplicateComponentName`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers?.['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Creates the specified overlay template.
         * @param {CalendarOverlayTemplateCreateDTO} [body] The overlay template.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calendarOverlayTemplateCreate: async (body?: CalendarOverlayTemplateCreateDTO, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/CalendarOverlayTemplate/Create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers?.['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes the specified identifier.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calendarOverlayTemplateDelete: async (id: string, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling calendarOverlayTemplateDelete.');
            }
            const localVarPath = `/api/CalendarOverlayTemplate/Delete/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets the specified identifier.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calendarOverlayTemplateGet: async (id: string, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling calendarOverlayTemplateGet.');
            }
            const localVarPath = `/api/CalendarOverlayTemplate/Get/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Lists the specified search.
         * @param {CalendarOverlayTemplateSearchDTO} [body] The search.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calendarOverlayTemplateList: async (body?: CalendarOverlayTemplateSearchDTO, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/CalendarOverlayTemplate/List`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers?.['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Restores the template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calendarOverlayTemplateRestore: async (id: string, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling calendarOverlayTemplateRestore.');
            }
            const localVarPath = `/api/CalendarOverlayTemplate/Restore/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Updates the specified overlay template.
         * @param {CalendarOverlayTemplateUpdateDTO} [body] The overlay template.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calendarOverlayTemplateUpdate: async (body?: CalendarOverlayTemplateUpdateDTO, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/CalendarOverlayTemplate/Update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers?.['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CalendarOverlayTemplateApi - functional programming interface
 * @export
 */
export const CalendarOverlayTemplateApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Check the duplicate calendar overlay component name.
         * @param {DuplicateNameCheckDto} [body] The duplicate name check Dto.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async calendarOverlayTemplateCheckDuplicateComponentName(body?: DuplicateNameCheckDto, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<boolean>>> {
            const localVarAxiosArgs = await CalendarOverlayTemplateApiAxiosParamCreator(configuration).calendarOverlayTemplateCheckDuplicateComponentName(body, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Creates the specified overlay template.
         * @param {CalendarOverlayTemplateCreateDTO} [body] The overlay template.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async calendarOverlayTemplateCreate(body?: CalendarOverlayTemplateCreateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CalendarOverlayTemplateDetailsDTO>>> {
            const localVarAxiosArgs = await CalendarOverlayTemplateApiAxiosParamCreator(configuration).calendarOverlayTemplateCreate(body, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Deletes the specified identifier.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async calendarOverlayTemplateDelete(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CalendarOverlayTemplateInfoDTO>>> {
            const localVarAxiosArgs = await CalendarOverlayTemplateApiAxiosParamCreator(configuration).calendarOverlayTemplateDelete(id, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Gets the specified identifier.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async calendarOverlayTemplateGet(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CalendarOverlayTemplateDetailsDTO>>> {
            const localVarAxiosArgs = await CalendarOverlayTemplateApiAxiosParamCreator(configuration).calendarOverlayTemplateGet(id, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Lists the specified search.
         * @param {CalendarOverlayTemplateSearchDTO} [body] The search.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async calendarOverlayTemplateList(body?: CalendarOverlayTemplateSearchDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CalendarOverlayTemplateInfoListDTO>>> {
            const localVarAxiosArgs = await CalendarOverlayTemplateApiAxiosParamCreator(configuration).calendarOverlayTemplateList(body, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Restores the template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async calendarOverlayTemplateRestore(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CalendarOverlayTemplateInfoDTO>>> {
            const localVarAxiosArgs = await CalendarOverlayTemplateApiAxiosParamCreator(configuration).calendarOverlayTemplateRestore(id, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Updates the specified overlay template.
         * @param {CalendarOverlayTemplateUpdateDTO} [body] The overlay template.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async calendarOverlayTemplateUpdate(body?: CalendarOverlayTemplateUpdateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CalendarOverlayTemplateDetailsDTO>>> {
            const localVarAxiosArgs = await CalendarOverlayTemplateApiAxiosParamCreator(configuration).calendarOverlayTemplateUpdate(body, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * CalendarOverlayTemplateApi - factory interface
 * @export
 */
export const CalendarOverlayTemplateApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Check the duplicate calendar overlay component name.
         * @param {DuplicateNameCheckDto} [body] The duplicate name check Dto.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async calendarOverlayTemplateCheckDuplicateComponentName(body?: DuplicateNameCheckDto, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<boolean>> {
            return CalendarOverlayTemplateApiFp(configuration).calendarOverlayTemplateCheckDuplicateComponentName(body, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Creates the specified overlay template.
         * @param {CalendarOverlayTemplateCreateDTO} [body] The overlay template.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async calendarOverlayTemplateCreate(body?: CalendarOverlayTemplateCreateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<CalendarOverlayTemplateDetailsDTO>> {
            return CalendarOverlayTemplateApiFp(configuration).calendarOverlayTemplateCreate(body, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes the specified identifier.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async calendarOverlayTemplateDelete(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<CalendarOverlayTemplateInfoDTO>> {
            return CalendarOverlayTemplateApiFp(configuration).calendarOverlayTemplateDelete(id, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets the specified identifier.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async calendarOverlayTemplateGet(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<CalendarOverlayTemplateDetailsDTO>> {
            return CalendarOverlayTemplateApiFp(configuration).calendarOverlayTemplateGet(id, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Lists the specified search.
         * @param {CalendarOverlayTemplateSearchDTO} [body] The search.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async calendarOverlayTemplateList(body?: CalendarOverlayTemplateSearchDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<CalendarOverlayTemplateInfoListDTO>> {
            return CalendarOverlayTemplateApiFp(configuration).calendarOverlayTemplateList(body, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Restores the template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async calendarOverlayTemplateRestore(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<CalendarOverlayTemplateInfoDTO>> {
            return CalendarOverlayTemplateApiFp(configuration).calendarOverlayTemplateRestore(id, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Updates the specified overlay template.
         * @param {CalendarOverlayTemplateUpdateDTO} [body] The overlay template.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async calendarOverlayTemplateUpdate(body?: CalendarOverlayTemplateUpdateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<CalendarOverlayTemplateDetailsDTO>> {
            return CalendarOverlayTemplateApiFp(configuration).calendarOverlayTemplateUpdate(body, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CalendarOverlayTemplateApi - object-oriented interface
 * @export
 * @class CalendarOverlayTemplateApi
 * @extends {BaseAPI}
 */
export class CalendarOverlayTemplateApi extends BaseAPI {
    /**
     * 
     * @summary Check the duplicate calendar overlay component name.
     * @param {DuplicateNameCheckDto} [body] The duplicate name check Dto.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CalendarOverlayTemplateApi
     */
    public async calendarOverlayTemplateCheckDuplicateComponentName(body?: DuplicateNameCheckDto, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<boolean>> {
        return CalendarOverlayTemplateApiFp(this.configuration).calendarOverlayTemplateCheckDuplicateComponentName(body, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Creates the specified overlay template.
     * @param {CalendarOverlayTemplateCreateDTO} [body] The overlay template.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CalendarOverlayTemplateApi
     */
    public async calendarOverlayTemplateCreate(body?: CalendarOverlayTemplateCreateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<CalendarOverlayTemplateDetailsDTO>> {
        return CalendarOverlayTemplateApiFp(this.configuration).calendarOverlayTemplateCreate(body, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Deletes the specified identifier.
     * @param {string} id The identifier.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CalendarOverlayTemplateApi
     */
    public async calendarOverlayTemplateDelete(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<CalendarOverlayTemplateInfoDTO>> {
        return CalendarOverlayTemplateApiFp(this.configuration).calendarOverlayTemplateDelete(id, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Gets the specified identifier.
     * @param {string} id The identifier.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CalendarOverlayTemplateApi
     */
    public async calendarOverlayTemplateGet(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<CalendarOverlayTemplateDetailsDTO>> {
        return CalendarOverlayTemplateApiFp(this.configuration).calendarOverlayTemplateGet(id, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Lists the specified search.
     * @param {CalendarOverlayTemplateSearchDTO} [body] The search.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CalendarOverlayTemplateApi
     */
    public async calendarOverlayTemplateList(body?: CalendarOverlayTemplateSearchDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<CalendarOverlayTemplateInfoListDTO>> {
        return CalendarOverlayTemplateApiFp(this.configuration).calendarOverlayTemplateList(body, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Restores the template.
     * @param {string} id The identifier.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CalendarOverlayTemplateApi
     */
    public async calendarOverlayTemplateRestore(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<CalendarOverlayTemplateInfoDTO>> {
        return CalendarOverlayTemplateApiFp(this.configuration).calendarOverlayTemplateRestore(id, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Updates the specified overlay template.
     * @param {CalendarOverlayTemplateUpdateDTO} [body] The overlay template.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CalendarOverlayTemplateApi
     */
    public async calendarOverlayTemplateUpdate(body?: CalendarOverlayTemplateUpdateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<CalendarOverlayTemplateDetailsDTO>> {
        return CalendarOverlayTemplateApiFp(this.configuration).calendarOverlayTemplateUpdate(body, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
}
