/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { DataDictionaryColumnDetailsDTO } from '../models';
import { DataDictionaryDTO } from '../models';
import { DisplaySource } from '../models';
import { ExceptionDTO } from '../models';
/**
 * DataDictionaryApi - axios parameter creator
 * @export
 */
export const DataDictionaryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Gets the complete data dictionary.
         * @param {string} omniClientId The omni client identifier.
         * @param {DisplaySource} [displaySource] The display source.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dataDictionaryGet: async (omniClientId: string, displaySource?: DisplaySource, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'omniClientId' is not null or undefined
            if (omniClientId === null || omniClientId === undefined) {
                throw new RequiredError('omniClientId','Required parameter omniClientId was null or undefined when calling dataDictionaryGet.');
            }
            const localVarPath = `/api/DataDictionary/Get/{omniClientId}`
                .replace(`{${"omniClientId"}}`, encodeURIComponent(String(omniClientId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (displaySource !== undefined) {
                localVarQueryParameter['displaySource'] = displaySource;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets the broadcast calendar columns.
         * @param {string} omniClientId The omni client identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dataDictionaryGetBroadcastCalendarColumns: async (omniClientId: string, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'omniClientId' is not null or undefined
            if (omniClientId === null || omniClientId === undefined) {
                throw new RequiredError('omniClientId','Required parameter omniClientId was null or undefined when calling dataDictionaryGetBroadcastCalendarColumns.');
            }
            const localVarPath = `/api/DataDictionary/GetBroadcastCalendarColumns/{omniClientId}`
                .replace(`{${"omniClientId"}}`, encodeURIComponent(String(omniClientId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets the client calendar columns.
         * @param {string} omniClientId The omni client identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dataDictionaryGetClientCalendarColumns: async (omniClientId: string, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'omniClientId' is not null or undefined
            if (omniClientId === null || omniClientId === undefined) {
                throw new RequiredError('omniClientId','Required parameter omniClientId was null or undefined when calling dataDictionaryGetClientCalendarColumns.');
            }
            const localVarPath = `/api/DataDictionary/GetClientCalendarColumns/{omniClientId}`
                .replace(`{${"omniClientId"}}`, encodeURIComponent(String(omniClientId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Refresh the DataDictionary Tables data manually.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dataDictionaryRefreshDataDictionaryTables: async (X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/DataDictionary/RefreshDataDictionaryTables`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update the client details by ClientId.
         * @param {string} [omniClientId] The omni client id identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dataDictionaryUpdateClientDetailsByOmniClientId: async (omniClientId?: string, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/DataDictionary/UpdateClientDetailsByOmniClientId`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (omniClientId !== undefined) {
                localVarQueryParameter['omniClientId'] = omniClientId;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DataDictionaryApi - functional programming interface
 * @export
 */
export const DataDictionaryApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Gets the complete data dictionary.
         * @param {string} omniClientId The omni client identifier.
         * @param {DisplaySource} [displaySource] The display source.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dataDictionaryGet(omniClientId: string, displaySource?: DisplaySource, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<DataDictionaryDTO>>> {
            const localVarAxiosArgs = await DataDictionaryApiAxiosParamCreator(configuration).dataDictionaryGet(omniClientId, displaySource, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Gets the broadcast calendar columns.
         * @param {string} omniClientId The omni client identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dataDictionaryGetBroadcastCalendarColumns(omniClientId: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<DataDictionaryColumnDetailsDTO>>>> {
            const localVarAxiosArgs = await DataDictionaryApiAxiosParamCreator(configuration).dataDictionaryGetBroadcastCalendarColumns(omniClientId, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Gets the client calendar columns.
         * @param {string} omniClientId The omni client identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dataDictionaryGetClientCalendarColumns(omniClientId: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<DataDictionaryColumnDetailsDTO>>>> {
            const localVarAxiosArgs = await DataDictionaryApiAxiosParamCreator(configuration).dataDictionaryGetClientCalendarColumns(omniClientId, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Refresh the DataDictionary Tables data manually.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dataDictionaryRefreshDataDictionaryTables(X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<string>>> {
            const localVarAxiosArgs = await DataDictionaryApiAxiosParamCreator(configuration).dataDictionaryRefreshDataDictionaryTables(X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Update the client details by ClientId.
         * @param {string} [omniClientId] The omni client id identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dataDictionaryUpdateClientDetailsByOmniClientId(omniClientId?: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await DataDictionaryApiAxiosParamCreator(configuration).dataDictionaryUpdateClientDetailsByOmniClientId(omniClientId, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DataDictionaryApi - factory interface
 * @export
 */
export const DataDictionaryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Gets the complete data dictionary.
         * @param {string} omniClientId The omni client identifier.
         * @param {DisplaySource} [displaySource] The display source.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dataDictionaryGet(omniClientId: string, displaySource?: DisplaySource, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<DataDictionaryDTO>> {
            return DataDictionaryApiFp(configuration).dataDictionaryGet(omniClientId, displaySource, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets the broadcast calendar columns.
         * @param {string} omniClientId The omni client identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dataDictionaryGetBroadcastCalendarColumns(omniClientId: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<DataDictionaryColumnDetailsDTO>>> {
            return DataDictionaryApiFp(configuration).dataDictionaryGetBroadcastCalendarColumns(omniClientId, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets the client calendar columns.
         * @param {string} omniClientId The omni client identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dataDictionaryGetClientCalendarColumns(omniClientId: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<DataDictionaryColumnDetailsDTO>>> {
            return DataDictionaryApiFp(configuration).dataDictionaryGetClientCalendarColumns(omniClientId, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Refresh the DataDictionary Tables data manually.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dataDictionaryRefreshDataDictionaryTables(X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<string>> {
            return DataDictionaryApiFp(configuration).dataDictionaryRefreshDataDictionaryTables(X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update the client details by ClientId.
         * @param {string} [omniClientId] The omni client id identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dataDictionaryUpdateClientDetailsByOmniClientId(omniClientId?: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return DataDictionaryApiFp(configuration).dataDictionaryUpdateClientDetailsByOmniClientId(omniClientId, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DataDictionaryApi - object-oriented interface
 * @export
 * @class DataDictionaryApi
 * @extends {BaseAPI}
 */
export class DataDictionaryApi extends BaseAPI {
    /**
     * 
     * @summary Gets the complete data dictionary.
     * @param {string} omniClientId The omni client identifier.
     * @param {DisplaySource} [displaySource] The display source.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DataDictionaryApi
     */
    public async dataDictionaryGet(omniClientId: string, displaySource?: DisplaySource, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<DataDictionaryDTO>> {
        return DataDictionaryApiFp(this.configuration).dataDictionaryGet(omniClientId, displaySource, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Gets the broadcast calendar columns.
     * @param {string} omniClientId The omni client identifier.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DataDictionaryApi
     */
    public async dataDictionaryGetBroadcastCalendarColumns(omniClientId: string, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<DataDictionaryColumnDetailsDTO>>> {
        return DataDictionaryApiFp(this.configuration).dataDictionaryGetBroadcastCalendarColumns(omniClientId, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Gets the client calendar columns.
     * @param {string} omniClientId The omni client identifier.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DataDictionaryApi
     */
    public async dataDictionaryGetClientCalendarColumns(omniClientId: string, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<DataDictionaryColumnDetailsDTO>>> {
        return DataDictionaryApiFp(this.configuration).dataDictionaryGetClientCalendarColumns(omniClientId, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Refresh the DataDictionary Tables data manually.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DataDictionaryApi
     */
    public async dataDictionaryRefreshDataDictionaryTables(X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<string>> {
        return DataDictionaryApiFp(this.configuration).dataDictionaryRefreshDataDictionaryTables(X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Update the client details by ClientId.
     * @param {string} [omniClientId] The omni client id identifier.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DataDictionaryApi
     */
    public async dataDictionaryUpdateClientDetailsByOmniClientId(omniClientId?: string, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return DataDictionaryApiFp(this.configuration).dataDictionaryUpdateClientDetailsByOmniClientId(omniClientId, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
}
