/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { DuplicateNameCheckDto } from '../models';
import { ExceptionDTO } from '../models';
import { MediaHierarchyTemplateCreateDTO } from '../models';
import { MediaHierarchyTemplateDetailsDTO } from '../models';
import { MediaHierarchyTemplateInfoDTO } from '../models';
import { MediaHierarchyTemplateInfoListDTO } from '../models';
import { MediaHierarchyTemplateSearchDTO } from '../models';
import { MediaHierarchyTemplateUpdateDTO } from '../models';
/**
 * MediaHierarchyTemplateApi - axios parameter creator
 * @export
 */
export const MediaHierarchyTemplateApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Check the duplicate media hierarchy component name.
         * @param {DuplicateNameCheckDto} [body] The duplicate name check Dto.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mediaHierarchyTemplateCheckDuplicateComponentName: async (body?: DuplicateNameCheckDto, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/MediaHierarchyTemplate/CheckDuplicateComponentName`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers?.['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Creates the media hierarchy template.
         * @param {MediaHierarchyTemplateCreateDTO} [body] The media hierarchy template.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mediaHierarchyTemplateCreate: async (body?: MediaHierarchyTemplateCreateDTO, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/MediaHierarchyTemplate/Create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers?.['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes the media hierarchy template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mediaHierarchyTemplateDelete: async (id: string, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling mediaHierarchyTemplateDelete.');
            }
            const localVarPath = `/api/MediaHierarchyTemplate/Delete/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets the media hierarchy template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mediaHierarchyTemplateGet: async (id: string, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling mediaHierarchyTemplateGet.');
            }
            const localVarPath = `/api/MediaHierarchyTemplate/Get/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Lists the media hierarchy templates.
         * @param {MediaHierarchyTemplateSearchDTO} [body] The search.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mediaHierarchyTemplateList: async (body?: MediaHierarchyTemplateSearchDTO, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/MediaHierarchyTemplate/List`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers?.['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Restores the template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mediaHierarchyTemplateRestore: async (id: string, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling mediaHierarchyTemplateRestore.');
            }
            const localVarPath = `/api/MediaHierarchyTemplate/Restore/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Updates the media hierarchy template.
         * @param {MediaHierarchyTemplateUpdateDTO} [body] The media hierarchy template.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        mediaHierarchyTemplateUpdate: async (body?: MediaHierarchyTemplateUpdateDTO, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/MediaHierarchyTemplate/Update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers?.['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MediaHierarchyTemplateApi - functional programming interface
 * @export
 */
export const MediaHierarchyTemplateApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Check the duplicate media hierarchy component name.
         * @param {DuplicateNameCheckDto} [body] The duplicate name check Dto.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mediaHierarchyTemplateCheckDuplicateComponentName(body?: DuplicateNameCheckDto, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<boolean>>> {
            const localVarAxiosArgs = await MediaHierarchyTemplateApiAxiosParamCreator(configuration).mediaHierarchyTemplateCheckDuplicateComponentName(body, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Creates the media hierarchy template.
         * @param {MediaHierarchyTemplateCreateDTO} [body] The media hierarchy template.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mediaHierarchyTemplateCreate(body?: MediaHierarchyTemplateCreateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<MediaHierarchyTemplateDetailsDTO>>> {
            const localVarAxiosArgs = await MediaHierarchyTemplateApiAxiosParamCreator(configuration).mediaHierarchyTemplateCreate(body, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Deletes the media hierarchy template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mediaHierarchyTemplateDelete(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<MediaHierarchyTemplateInfoDTO>>> {
            const localVarAxiosArgs = await MediaHierarchyTemplateApiAxiosParamCreator(configuration).mediaHierarchyTemplateDelete(id, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Gets the media hierarchy template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mediaHierarchyTemplateGet(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<MediaHierarchyTemplateDetailsDTO>>> {
            const localVarAxiosArgs = await MediaHierarchyTemplateApiAxiosParamCreator(configuration).mediaHierarchyTemplateGet(id, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Lists the media hierarchy templates.
         * @param {MediaHierarchyTemplateSearchDTO} [body] The search.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mediaHierarchyTemplateList(body?: MediaHierarchyTemplateSearchDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<MediaHierarchyTemplateInfoListDTO>>> {
            const localVarAxiosArgs = await MediaHierarchyTemplateApiAxiosParamCreator(configuration).mediaHierarchyTemplateList(body, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Restores the template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mediaHierarchyTemplateRestore(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<MediaHierarchyTemplateInfoDTO>>> {
            const localVarAxiosArgs = await MediaHierarchyTemplateApiAxiosParamCreator(configuration).mediaHierarchyTemplateRestore(id, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Updates the media hierarchy template.
         * @param {MediaHierarchyTemplateUpdateDTO} [body] The media hierarchy template.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mediaHierarchyTemplateUpdate(body?: MediaHierarchyTemplateUpdateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<MediaHierarchyTemplateDetailsDTO>>> {
            const localVarAxiosArgs = await MediaHierarchyTemplateApiAxiosParamCreator(configuration).mediaHierarchyTemplateUpdate(body, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * MediaHierarchyTemplateApi - factory interface
 * @export
 */
export const MediaHierarchyTemplateApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Check the duplicate media hierarchy component name.
         * @param {DuplicateNameCheckDto} [body] The duplicate name check Dto.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mediaHierarchyTemplateCheckDuplicateComponentName(body?: DuplicateNameCheckDto, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<boolean>> {
            return MediaHierarchyTemplateApiFp(configuration).mediaHierarchyTemplateCheckDuplicateComponentName(body, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Creates the media hierarchy template.
         * @param {MediaHierarchyTemplateCreateDTO} [body] The media hierarchy template.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mediaHierarchyTemplateCreate(body?: MediaHierarchyTemplateCreateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<MediaHierarchyTemplateDetailsDTO>> {
            return MediaHierarchyTemplateApiFp(configuration).mediaHierarchyTemplateCreate(body, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes the media hierarchy template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mediaHierarchyTemplateDelete(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<MediaHierarchyTemplateInfoDTO>> {
            return MediaHierarchyTemplateApiFp(configuration).mediaHierarchyTemplateDelete(id, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets the media hierarchy template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mediaHierarchyTemplateGet(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<MediaHierarchyTemplateDetailsDTO>> {
            return MediaHierarchyTemplateApiFp(configuration).mediaHierarchyTemplateGet(id, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Lists the media hierarchy templates.
         * @param {MediaHierarchyTemplateSearchDTO} [body] The search.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mediaHierarchyTemplateList(body?: MediaHierarchyTemplateSearchDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<MediaHierarchyTemplateInfoListDTO>> {
            return MediaHierarchyTemplateApiFp(configuration).mediaHierarchyTemplateList(body, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Restores the template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mediaHierarchyTemplateRestore(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<MediaHierarchyTemplateInfoDTO>> {
            return MediaHierarchyTemplateApiFp(configuration).mediaHierarchyTemplateRestore(id, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Updates the media hierarchy template.
         * @param {MediaHierarchyTemplateUpdateDTO} [body] The media hierarchy template.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async mediaHierarchyTemplateUpdate(body?: MediaHierarchyTemplateUpdateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<MediaHierarchyTemplateDetailsDTO>> {
            return MediaHierarchyTemplateApiFp(configuration).mediaHierarchyTemplateUpdate(body, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MediaHierarchyTemplateApi - object-oriented interface
 * @export
 * @class MediaHierarchyTemplateApi
 * @extends {BaseAPI}
 */
export class MediaHierarchyTemplateApi extends BaseAPI {
    /**
     * 
     * @summary Check the duplicate media hierarchy component name.
     * @param {DuplicateNameCheckDto} [body] The duplicate name check Dto.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaHierarchyTemplateApi
     */
    public async mediaHierarchyTemplateCheckDuplicateComponentName(body?: DuplicateNameCheckDto, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<boolean>> {
        return MediaHierarchyTemplateApiFp(this.configuration).mediaHierarchyTemplateCheckDuplicateComponentName(body, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Creates the media hierarchy template.
     * @param {MediaHierarchyTemplateCreateDTO} [body] The media hierarchy template.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaHierarchyTemplateApi
     */
    public async mediaHierarchyTemplateCreate(body?: MediaHierarchyTemplateCreateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<MediaHierarchyTemplateDetailsDTO>> {
        return MediaHierarchyTemplateApiFp(this.configuration).mediaHierarchyTemplateCreate(body, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Deletes the media hierarchy template.
     * @param {string} id The identifier.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaHierarchyTemplateApi
     */
    public async mediaHierarchyTemplateDelete(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<MediaHierarchyTemplateInfoDTO>> {
        return MediaHierarchyTemplateApiFp(this.configuration).mediaHierarchyTemplateDelete(id, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Gets the media hierarchy template.
     * @param {string} id The identifier.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaHierarchyTemplateApi
     */
    public async mediaHierarchyTemplateGet(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<MediaHierarchyTemplateDetailsDTO>> {
        return MediaHierarchyTemplateApiFp(this.configuration).mediaHierarchyTemplateGet(id, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Lists the media hierarchy templates.
     * @param {MediaHierarchyTemplateSearchDTO} [body] The search.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaHierarchyTemplateApi
     */
    public async mediaHierarchyTemplateList(body?: MediaHierarchyTemplateSearchDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<MediaHierarchyTemplateInfoListDTO>> {
        return MediaHierarchyTemplateApiFp(this.configuration).mediaHierarchyTemplateList(body, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Restores the template.
     * @param {string} id The identifier.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaHierarchyTemplateApi
     */
    public async mediaHierarchyTemplateRestore(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<MediaHierarchyTemplateInfoDTO>> {
        return MediaHierarchyTemplateApiFp(this.configuration).mediaHierarchyTemplateRestore(id, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Updates the media hierarchy template.
     * @param {MediaHierarchyTemplateUpdateDTO} [body] The media hierarchy template.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaHierarchyTemplateApi
     */
    public async mediaHierarchyTemplateUpdate(body?: MediaHierarchyTemplateUpdateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<MediaHierarchyTemplateDetailsDTO>> {
        return MediaHierarchyTemplateApiFp(this.configuration).mediaHierarchyTemplateUpdate(body, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
}
