/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ExceptionDTO } from '../models';
import { RunConfigurationCreateDTO } from '../models';
import { RunConfigurationDetailsDTO } from '../models';
import { RunConfigurationInfoDTO } from '../models';
import { RunConfigurationInfoListDTO } from '../models';
import { RunConfigurationSearchDTO } from '../models';
import { RunConfigurationUpdateDTO } from '../models';
/**
 * RunConfigurationApi - axios parameter creator
 * @export
 */
export const RunConfigurationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Creates the specified run configuration.
         * @param {RunConfigurationCreateDTO} [body] The run configuration.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runConfigurationCreate: async (body?: RunConfigurationCreateDTO, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/RunConfiguration/Create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers?.['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes the specified run configuration.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runConfigurationDelete: async (id: string, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling runConfigurationDelete.');
            }
            const localVarPath = `/api/RunConfiguration/Delete/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets the specified run configuration.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runConfigurationGet: async (id: string, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling runConfigurationGet.');
            }
            const localVarPath = `/api/RunConfiguration/Get/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Lists the specified search.
         * @param {RunConfigurationSearchDTO} [body] The search.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runConfigurationList: async (body?: RunConfigurationSearchDTO, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/RunConfiguration/List`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers?.['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Updates the specified run configuration.
         * @param {RunConfigurationUpdateDTO} [body] The run configuration.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runConfigurationUpdate: async (body?: RunConfigurationUpdateDTO, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/RunConfiguration/Update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers?.['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RunConfigurationApi - functional programming interface
 * @export
 */
export const RunConfigurationApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Creates the specified run configuration.
         * @param {RunConfigurationCreateDTO} [body] The run configuration.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runConfigurationCreate(body?: RunConfigurationCreateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RunConfigurationDetailsDTO>>> {
            const localVarAxiosArgs = await RunConfigurationApiAxiosParamCreator(configuration).runConfigurationCreate(body, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Deletes the specified run configuration.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runConfigurationDelete(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RunConfigurationInfoDTO>>> {
            const localVarAxiosArgs = await RunConfigurationApiAxiosParamCreator(configuration).runConfigurationDelete(id, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Gets the specified run configuration.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runConfigurationGet(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RunConfigurationDetailsDTO>>> {
            const localVarAxiosArgs = await RunConfigurationApiAxiosParamCreator(configuration).runConfigurationGet(id, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Lists the specified search.
         * @param {RunConfigurationSearchDTO} [body] The search.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runConfigurationList(body?: RunConfigurationSearchDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RunConfigurationInfoListDTO>>> {
            const localVarAxiosArgs = await RunConfigurationApiAxiosParamCreator(configuration).runConfigurationList(body, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Updates the specified run configuration.
         * @param {RunConfigurationUpdateDTO} [body] The run configuration.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runConfigurationUpdate(body?: RunConfigurationUpdateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RunConfigurationDetailsDTO>>> {
            const localVarAxiosArgs = await RunConfigurationApiAxiosParamCreator(configuration).runConfigurationUpdate(body, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * RunConfigurationApi - factory interface
 * @export
 */
export const RunConfigurationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Creates the specified run configuration.
         * @param {RunConfigurationCreateDTO} [body] The run configuration.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runConfigurationCreate(body?: RunConfigurationCreateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<RunConfigurationDetailsDTO>> {
            return RunConfigurationApiFp(configuration).runConfigurationCreate(body, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes the specified run configuration.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runConfigurationDelete(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<RunConfigurationInfoDTO>> {
            return RunConfigurationApiFp(configuration).runConfigurationDelete(id, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets the specified run configuration.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runConfigurationGet(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<RunConfigurationDetailsDTO>> {
            return RunConfigurationApiFp(configuration).runConfigurationGet(id, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Lists the specified search.
         * @param {RunConfigurationSearchDTO} [body] The search.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runConfigurationList(body?: RunConfigurationSearchDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<RunConfigurationInfoListDTO>> {
            return RunConfigurationApiFp(configuration).runConfigurationList(body, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Updates the specified run configuration.
         * @param {RunConfigurationUpdateDTO} [body] The run configuration.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runConfigurationUpdate(body?: RunConfigurationUpdateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<RunConfigurationDetailsDTO>> {
            return RunConfigurationApiFp(configuration).runConfigurationUpdate(body, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RunConfigurationApi - object-oriented interface
 * @export
 * @class RunConfigurationApi
 * @extends {BaseAPI}
 */
export class RunConfigurationApi extends BaseAPI {
    /**
     * 
     * @summary Creates the specified run configuration.
     * @param {RunConfigurationCreateDTO} [body] The run configuration.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RunConfigurationApi
     */
    public async runConfigurationCreate(body?: RunConfigurationCreateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<RunConfigurationDetailsDTO>> {
        return RunConfigurationApiFp(this.configuration).runConfigurationCreate(body, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Deletes the specified run configuration.
     * @param {string} id The identifier.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RunConfigurationApi
     */
    public async runConfigurationDelete(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<RunConfigurationInfoDTO>> {
        return RunConfigurationApiFp(this.configuration).runConfigurationDelete(id, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Gets the specified run configuration.
     * @param {string} id The identifier.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RunConfigurationApi
     */
    public async runConfigurationGet(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<RunConfigurationDetailsDTO>> {
        return RunConfigurationApiFp(this.configuration).runConfigurationGet(id, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Lists the specified search.
     * @param {RunConfigurationSearchDTO} [body] The search.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RunConfigurationApi
     */
    public async runConfigurationList(body?: RunConfigurationSearchDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<RunConfigurationInfoListDTO>> {
        return RunConfigurationApiFp(this.configuration).runConfigurationList(body, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Updates the specified run configuration.
     * @param {RunConfigurationUpdateDTO} [body] The run configuration.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RunConfigurationApi
     */
    public async runConfigurationUpdate(body?: RunConfigurationUpdateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<RunConfigurationDetailsDTO>> {
        return RunConfigurationApiFp(this.configuration).runConfigurationUpdate(body, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
}
