/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { DuplicateNameCheckDto } from '../models';
import { ExceptionDTO } from '../models';
import { ThemeTemplateCreateDTO } from '../models';
import { ThemeTemplateDetailsDTO } from '../models';
import { ThemeTemplateInfoDTO } from '../models';
import { ThemeTemplateInfoListDTO } from '../models';
import { ThemeTemplateSearchDTO } from '../models';
import { ThemeTemplateUpdateDTO } from '../models';
/**
 * ThemeTemplateApi - axios parameter creator
 * @export
 */
export const ThemeTemplateApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Check the duplicate Theme component name.
         * @param {DuplicateNameCheckDto} [body] The duplicate name check Dto.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        themeTemplateCheckDuplicateComponentName: async (body?: DuplicateNameCheckDto, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/ThemeTemplate/CheckDuplicateComponentName`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers?.['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Creates the specified theme template.
         * @param {ThemeTemplateCreateDTO} [body] The theme template.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        themeTemplateCreate: async (body?: ThemeTemplateCreateDTO, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/ThemeTemplate/Create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers?.['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes the specified theme template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        themeTemplateDelete: async (id: string, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling themeTemplateDelete.');
            }
            const localVarPath = `/api/ThemeTemplate/Delete/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets the specified theme template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        themeTemplateGet: async (id: string, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling themeTemplateGet.');
            }
            const localVarPath = `/api/ThemeTemplate/Get/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Lists the theme templates.
         * @param {ThemeTemplateSearchDTO} [body] The search.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        themeTemplateList: async (body?: ThemeTemplateSearchDTO, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/ThemeTemplate/List`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers?.['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Restores the template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        themeTemplateRestore: async (id: string, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling themeTemplateRestore.');
            }
            const localVarPath = `/api/ThemeTemplate/Restore/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Updates the specified theme template.
         * @param {ThemeTemplateUpdateDTO} [body] The theme template.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        themeTemplateUpdate: async (body?: ThemeTemplateUpdateDTO, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/ThemeTemplate/Update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers?.['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ThemeTemplateApi - functional programming interface
 * @export
 */
export const ThemeTemplateApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Check the duplicate Theme component name.
         * @param {DuplicateNameCheckDto} [body] The duplicate name check Dto.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async themeTemplateCheckDuplicateComponentName(body?: DuplicateNameCheckDto, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<boolean>>> {
            const localVarAxiosArgs = await ThemeTemplateApiAxiosParamCreator(configuration).themeTemplateCheckDuplicateComponentName(body, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Creates the specified theme template.
         * @param {ThemeTemplateCreateDTO} [body] The theme template.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async themeTemplateCreate(body?: ThemeTemplateCreateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ThemeTemplateDetailsDTO>>> {
            const localVarAxiosArgs = await ThemeTemplateApiAxiosParamCreator(configuration).themeTemplateCreate(body, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Deletes the specified theme template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async themeTemplateDelete(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ThemeTemplateInfoDTO>>> {
            const localVarAxiosArgs = await ThemeTemplateApiAxiosParamCreator(configuration).themeTemplateDelete(id, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Gets the specified theme template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async themeTemplateGet(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ThemeTemplateDetailsDTO>>> {
            const localVarAxiosArgs = await ThemeTemplateApiAxiosParamCreator(configuration).themeTemplateGet(id, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Lists the theme templates.
         * @param {ThemeTemplateSearchDTO} [body] The search.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async themeTemplateList(body?: ThemeTemplateSearchDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ThemeTemplateInfoListDTO>>> {
            const localVarAxiosArgs = await ThemeTemplateApiAxiosParamCreator(configuration).themeTemplateList(body, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Restores the template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async themeTemplateRestore(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ThemeTemplateInfoDTO>>> {
            const localVarAxiosArgs = await ThemeTemplateApiAxiosParamCreator(configuration).themeTemplateRestore(id, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Updates the specified theme template.
         * @param {ThemeTemplateUpdateDTO} [body] The theme template.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async themeTemplateUpdate(body?: ThemeTemplateUpdateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ThemeTemplateDetailsDTO>>> {
            const localVarAxiosArgs = await ThemeTemplateApiAxiosParamCreator(configuration).themeTemplateUpdate(body, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ThemeTemplateApi - factory interface
 * @export
 */
export const ThemeTemplateApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Check the duplicate Theme component name.
         * @param {DuplicateNameCheckDto} [body] The duplicate name check Dto.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async themeTemplateCheckDuplicateComponentName(body?: DuplicateNameCheckDto, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<boolean>> {
            return ThemeTemplateApiFp(configuration).themeTemplateCheckDuplicateComponentName(body, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Creates the specified theme template.
         * @param {ThemeTemplateCreateDTO} [body] The theme template.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async themeTemplateCreate(body?: ThemeTemplateCreateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<ThemeTemplateDetailsDTO>> {
            return ThemeTemplateApiFp(configuration).themeTemplateCreate(body, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes the specified theme template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async themeTemplateDelete(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<ThemeTemplateInfoDTO>> {
            return ThemeTemplateApiFp(configuration).themeTemplateDelete(id, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets the specified theme template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async themeTemplateGet(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<ThemeTemplateDetailsDTO>> {
            return ThemeTemplateApiFp(configuration).themeTemplateGet(id, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Lists the theme templates.
         * @param {ThemeTemplateSearchDTO} [body] The search.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async themeTemplateList(body?: ThemeTemplateSearchDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<ThemeTemplateInfoListDTO>> {
            return ThemeTemplateApiFp(configuration).themeTemplateList(body, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Restores the template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async themeTemplateRestore(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<ThemeTemplateInfoDTO>> {
            return ThemeTemplateApiFp(configuration).themeTemplateRestore(id, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Updates the specified theme template.
         * @param {ThemeTemplateUpdateDTO} [body] The theme template.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async themeTemplateUpdate(body?: ThemeTemplateUpdateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<ThemeTemplateDetailsDTO>> {
            return ThemeTemplateApiFp(configuration).themeTemplateUpdate(body, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ThemeTemplateApi - object-oriented interface
 * @export
 * @class ThemeTemplateApi
 * @extends {BaseAPI}
 */
export class ThemeTemplateApi extends BaseAPI {
    /**
     * 
     * @summary Check the duplicate Theme component name.
     * @param {DuplicateNameCheckDto} [body] The duplicate name check Dto.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ThemeTemplateApi
     */
    public async themeTemplateCheckDuplicateComponentName(body?: DuplicateNameCheckDto, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<boolean>> {
        return ThemeTemplateApiFp(this.configuration).themeTemplateCheckDuplicateComponentName(body, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Creates the specified theme template.
     * @param {ThemeTemplateCreateDTO} [body] The theme template.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ThemeTemplateApi
     */
    public async themeTemplateCreate(body?: ThemeTemplateCreateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<ThemeTemplateDetailsDTO>> {
        return ThemeTemplateApiFp(this.configuration).themeTemplateCreate(body, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Deletes the specified theme template.
     * @param {string} id The identifier.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ThemeTemplateApi
     */
    public async themeTemplateDelete(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<ThemeTemplateInfoDTO>> {
        return ThemeTemplateApiFp(this.configuration).themeTemplateDelete(id, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Gets the specified theme template.
     * @param {string} id The identifier.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ThemeTemplateApi
     */
    public async themeTemplateGet(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<ThemeTemplateDetailsDTO>> {
        return ThemeTemplateApiFp(this.configuration).themeTemplateGet(id, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Lists the theme templates.
     * @param {ThemeTemplateSearchDTO} [body] The search.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ThemeTemplateApi
     */
    public async themeTemplateList(body?: ThemeTemplateSearchDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<ThemeTemplateInfoListDTO>> {
        return ThemeTemplateApiFp(this.configuration).themeTemplateList(body, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Restores the template.
     * @param {string} id The identifier.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ThemeTemplateApi
     */
    public async themeTemplateRestore(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<ThemeTemplateInfoDTO>> {
        return ThemeTemplateApiFp(this.configuration).themeTemplateRestore(id, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Updates the specified theme template.
     * @param {ThemeTemplateUpdateDTO} [body] The theme template.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ThemeTemplateApi
     */
    public async themeTemplateUpdate(body?: ThemeTemplateUpdateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<ThemeTemplateDetailsDTO>> {
        return ThemeTemplateApiFp(this.configuration).themeTemplateUpdate(body, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
}
