/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { DuplicateNameCheckDto } from '../models';
import { ExceptionDTO } from '../models';
import { TotalsTemplateCreateDTO } from '../models';
import { TotalsTemplateDetailsDTO } from '../models';
import { TotalsTemplateInfoDTO } from '../models';
import { TotalsTemplateInfoListDTO } from '../models';
import { TotalsTemplateSearchDTO } from '../models';
import { TotalsTemplateUpdateDTO } from '../models';
/**
 * TotalsTemplateApi - axios parameter creator
 * @export
 */
export const TotalsTemplateApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Check the duplicate RightHandTotals component name.
         * @param {DuplicateNameCheckDto} [body] The duplicate name check Dto.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        totalsTemplateCheckDuplicateComponentName: async (body?: DuplicateNameCheckDto, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/TotalsTemplate/CheckDuplicateComponentName`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers?.['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Creates the specified totals template.
         * @param {TotalsTemplateCreateDTO} [body] The totals template.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        totalsTemplateCreate: async (body?: TotalsTemplateCreateDTO, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/TotalsTemplate/Create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers?.['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes the specified totals template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        totalsTemplateDelete: async (id: string, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling totalsTemplateDelete.');
            }
            const localVarPath = `/api/TotalsTemplate/Delete/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets the specified totals template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        totalsTemplateGet: async (id: string, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling totalsTemplateGet.');
            }
            const localVarPath = `/api/TotalsTemplate/Get/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Lists the specified search.
         * @param {TotalsTemplateSearchDTO} [body] The search.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        totalsTemplateList: async (body?: TotalsTemplateSearchDTO, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/TotalsTemplate/List`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers?.['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Restores the template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        totalsTemplateRestore: async (id: string, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling totalsTemplateRestore.');
            }
            const localVarPath = `/api/TotalsTemplate/Restore/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Updates the specified totals template.
         * @param {TotalsTemplateUpdateDTO} [body] The totals template.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        totalsTemplateUpdate: async (body?: TotalsTemplateUpdateDTO, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/TotalsTemplate/Update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers?.['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TotalsTemplateApi - functional programming interface
 * @export
 */
export const TotalsTemplateApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Check the duplicate RightHandTotals component name.
         * @param {DuplicateNameCheckDto} [body] The duplicate name check Dto.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async totalsTemplateCheckDuplicateComponentName(body?: DuplicateNameCheckDto, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<boolean>>> {
            const localVarAxiosArgs = await TotalsTemplateApiAxiosParamCreator(configuration).totalsTemplateCheckDuplicateComponentName(body, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Creates the specified totals template.
         * @param {TotalsTemplateCreateDTO} [body] The totals template.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async totalsTemplateCreate(body?: TotalsTemplateCreateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<TotalsTemplateDetailsDTO>>> {
            const localVarAxiosArgs = await TotalsTemplateApiAxiosParamCreator(configuration).totalsTemplateCreate(body, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Deletes the specified totals template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async totalsTemplateDelete(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<TotalsTemplateInfoDTO>>> {
            const localVarAxiosArgs = await TotalsTemplateApiAxiosParamCreator(configuration).totalsTemplateDelete(id, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Gets the specified totals template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async totalsTemplateGet(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<TotalsTemplateDetailsDTO>>> {
            const localVarAxiosArgs = await TotalsTemplateApiAxiosParamCreator(configuration).totalsTemplateGet(id, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Lists the specified search.
         * @param {TotalsTemplateSearchDTO} [body] The search.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async totalsTemplateList(body?: TotalsTemplateSearchDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<TotalsTemplateInfoListDTO>>> {
            const localVarAxiosArgs = await TotalsTemplateApiAxiosParamCreator(configuration).totalsTemplateList(body, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Restores the template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async totalsTemplateRestore(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<TotalsTemplateInfoDTO>>> {
            const localVarAxiosArgs = await TotalsTemplateApiAxiosParamCreator(configuration).totalsTemplateRestore(id, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Updates the specified totals template.
         * @param {TotalsTemplateUpdateDTO} [body] The totals template.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async totalsTemplateUpdate(body?: TotalsTemplateUpdateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<TotalsTemplateDetailsDTO>>> {
            const localVarAxiosArgs = await TotalsTemplateApiAxiosParamCreator(configuration).totalsTemplateUpdate(body, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * TotalsTemplateApi - factory interface
 * @export
 */
export const TotalsTemplateApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Check the duplicate RightHandTotals component name.
         * @param {DuplicateNameCheckDto} [body] The duplicate name check Dto.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async totalsTemplateCheckDuplicateComponentName(body?: DuplicateNameCheckDto, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<boolean>> {
            return TotalsTemplateApiFp(configuration).totalsTemplateCheckDuplicateComponentName(body, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Creates the specified totals template.
         * @param {TotalsTemplateCreateDTO} [body] The totals template.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async totalsTemplateCreate(body?: TotalsTemplateCreateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<TotalsTemplateDetailsDTO>> {
            return TotalsTemplateApiFp(configuration).totalsTemplateCreate(body, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes the specified totals template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async totalsTemplateDelete(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<TotalsTemplateInfoDTO>> {
            return TotalsTemplateApiFp(configuration).totalsTemplateDelete(id, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets the specified totals template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async totalsTemplateGet(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<TotalsTemplateDetailsDTO>> {
            return TotalsTemplateApiFp(configuration).totalsTemplateGet(id, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Lists the specified search.
         * @param {TotalsTemplateSearchDTO} [body] The search.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async totalsTemplateList(body?: TotalsTemplateSearchDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<TotalsTemplateInfoListDTO>> {
            return TotalsTemplateApiFp(configuration).totalsTemplateList(body, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Restores the template.
         * @param {string} id The identifier.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async totalsTemplateRestore(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<TotalsTemplateInfoDTO>> {
            return TotalsTemplateApiFp(configuration).totalsTemplateRestore(id, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Updates the specified totals template.
         * @param {TotalsTemplateUpdateDTO} [body] The totals template.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async totalsTemplateUpdate(body?: TotalsTemplateUpdateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<TotalsTemplateDetailsDTO>> {
            return TotalsTemplateApiFp(configuration).totalsTemplateUpdate(body, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TotalsTemplateApi - object-oriented interface
 * @export
 * @class TotalsTemplateApi
 * @extends {BaseAPI}
 */
export class TotalsTemplateApi extends BaseAPI {
    /**
     * 
     * @summary Check the duplicate RightHandTotals component name.
     * @param {DuplicateNameCheckDto} [body] The duplicate name check Dto.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TotalsTemplateApi
     */
    public async totalsTemplateCheckDuplicateComponentName(body?: DuplicateNameCheckDto, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<boolean>> {
        return TotalsTemplateApiFp(this.configuration).totalsTemplateCheckDuplicateComponentName(body, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Creates the specified totals template.
     * @param {TotalsTemplateCreateDTO} [body] The totals template.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TotalsTemplateApi
     */
    public async totalsTemplateCreate(body?: TotalsTemplateCreateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<TotalsTemplateDetailsDTO>> {
        return TotalsTemplateApiFp(this.configuration).totalsTemplateCreate(body, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Deletes the specified totals template.
     * @param {string} id The identifier.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TotalsTemplateApi
     */
    public async totalsTemplateDelete(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<TotalsTemplateInfoDTO>> {
        return TotalsTemplateApiFp(this.configuration).totalsTemplateDelete(id, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Gets the specified totals template.
     * @param {string} id The identifier.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TotalsTemplateApi
     */
    public async totalsTemplateGet(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<TotalsTemplateDetailsDTO>> {
        return TotalsTemplateApiFp(this.configuration).totalsTemplateGet(id, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Lists the specified search.
     * @param {TotalsTemplateSearchDTO} [body] The search.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TotalsTemplateApi
     */
    public async totalsTemplateList(body?: TotalsTemplateSearchDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<TotalsTemplateInfoListDTO>> {
        return TotalsTemplateApiFp(this.configuration).totalsTemplateList(body, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Restores the template.
     * @param {string} id The identifier.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TotalsTemplateApi
     */
    public async totalsTemplateRestore(id: string, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<TotalsTemplateInfoDTO>> {
        return TotalsTemplateApiFp(this.configuration).totalsTemplateRestore(id, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Updates the specified totals template.
     * @param {TotalsTemplateUpdateDTO} [body] The totals template.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TotalsTemplateApi
     */
    public async totalsTemplateUpdate(body?: TotalsTemplateUpdateDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<TotalsTemplateDetailsDTO>> {
        return TotalsTemplateApiFp(this.configuration).totalsTemplateUpdate(body, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
}
