/* tslint:disable */
/* eslint-disable */
/**
 * WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Generated by T4M 
 */
 
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ExceptionDTO } from '../models';
import { LoginDTO } from '../models';
import { UserDetailsDTO } from '../models';
import { ValidateSessionResponse } from '../models';
/**
 * UserApi - axios parameter creator
 * @export
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Gets the current user.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userCurrent: async (X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/User/Current`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Extend the current user token expiration time
         * @param {string} token Omni session token.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userExtendSession: async (token: string, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            if (token === null || token === undefined) {
                throw new RequiredError('token','Required parameter token was null or undefined when calling userExtendSession.');
            }
            const localVarPath = `/api/User/ExtendSession/{token}`
                .replace(`{${"token"}}`, encodeURIComponent(String(token)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Logins the specified user. For development only.
         * @param {LoginDTO} [body] The login.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userLogin: async (body?: LoginDTO, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/User/Login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers?.['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Validate the current user token
         * @param {string} token Omni session token.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userValidateToken: async (token: string, X_Correlation_Id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'token' is not null or undefined
            if (token === null || token === undefined) {
                throw new RequiredError('token','Required parameter token was null or undefined when calling userValidateToken.');
            }
            const localVarPath = `/api/User/ValidateToken/{token}`
                .replace(`{${"token"}}`, encodeURIComponent(String(token)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (X_Correlation_Id !== undefined && X_Correlation_Id !== null) {
                localVarHeaderParameter['X-Correlation-Id'] = String(X_Correlation_Id);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 * @export
 */
export const UserApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Gets the current user.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userCurrent(X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<UserDetailsDTO>>> {
            const localVarAxiosArgs = await UserApiAxiosParamCreator(configuration).userCurrent(X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Extend the current user token expiration time
         * @param {string} token Omni session token.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userExtendSession(token: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ValidateSessionResponse>>> {
            const localVarAxiosArgs = await UserApiAxiosParamCreator(configuration).userExtendSession(token, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Logins the specified user. For development only.
         * @param {LoginDTO} [body] The login.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userLogin(body?: LoginDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<string>>> {
            const localVarAxiosArgs = await UserApiAxiosParamCreator(configuration).userLogin(body, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Validate the current user token
         * @param {string} token Omni session token.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userValidateToken(token: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ValidateSessionResponse>>> {
            const localVarAxiosArgs = await UserApiAxiosParamCreator(configuration).userValidateToken(token, X_Correlation_Id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * UserApi - factory interface
 * @export
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Gets the current user.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userCurrent(X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<UserDetailsDTO>> {
            return UserApiFp(configuration).userCurrent(X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Extend the current user token expiration time
         * @param {string} token Omni session token.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userExtendSession(token: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<ValidateSessionResponse>> {
            return UserApiFp(configuration).userExtendSession(token, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Logins the specified user. For development only.
         * @param {LoginDTO} [body] The login.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userLogin(body?: LoginDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<string>> {
            return UserApiFp(configuration).userLogin(body, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Validate the current user token
         * @param {string} token Omni session token.
         * @param {string} [X_Correlation_Id] Correlation Id
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userValidateToken(token: string, X_Correlation_Id?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<ValidateSessionResponse>> {
            return UserApiFp(configuration).userValidateToken(token, X_Correlation_Id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 * @export
 * @class UserApi
 * @extends {BaseAPI}
 */
export class UserApi extends BaseAPI {
    /**
     * 
     * @summary Gets the current user.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public async userCurrent(X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<UserDetailsDTO>> {
        return UserApiFp(this.configuration).userCurrent(X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Extend the current user token expiration time
     * @param {string} token Omni session token.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public async userExtendSession(token: string, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<ValidateSessionResponse>> {
        return UserApiFp(this.configuration).userExtendSession(token, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Logins the specified user. For development only.
     * @param {LoginDTO} [body] The login.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public async userLogin(body?: LoginDTO, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<string>> {
        return UserApiFp(this.configuration).userLogin(body, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Validate the current user token
     * @param {string} token Omni session token.
     * @param {string} [X_Correlation_Id] Correlation Id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public async userValidateToken(token: string, X_Correlation_Id?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<ValidateSessionResponse>> {
        return UserApiFp(this.configuration).userValidateToken(token, X_Correlation_Id, options).then((request) => request(this.axios, this.basePath));
    }
}
